./compile_tests.sh addlarge
./compile_tests.sh addneg
./compile_tests.sh addpos
./compile_tests.sh bool
./compile_tests.sh branchcnt
./compile_tests.sh branchmany
./compile_tests.sh branchtrap
./compile_tests.sh loop
./compile_tests.sh recursive
./compile_tests.sh set
./compile_tests.sh shift
./compile_tests.sh shift2
./compile_tests.sh string
./compile_tests.sh t1
./compile_tests.sh t10
./compile_tests.sh t11
./compile_tests.sh t14
./compile_tests.sh t15
./compile_tests.sh t2
./compile_tests.sh t3
./compile_tests.sh t4
./compile_tests.sh t5
./compile_tests.sh t6
./compile_tests.sh t7
./compile_tests.sh t8
./compile_tests.sh t9
./compile_tests.sh width
